// AUTO-GENERATED Quran metadata (Mushaf al-Madinah, 604 pages). Do not edit by hand.
import Foundation

struct Surah: Identifiable, Hashable {
    let id: Int
    let arabic: String
    let english: String
    let meaning: String
    let place: String
    let ayahCount: Int
    let startPage: Int
}

enum QuranData {
    static let totalPages = 604

    static let surahs: [Surah] = [
        Surah(id: 1, arabic: "الفاتحة", english: "Al-Fatihah", meaning: "The Opener", place: "makkah", ayahCount: 7, startPage: 1),
        Surah(id: 2, arabic: "البقرة", english: "Al-Baqarah", meaning: "The Cow", place: "madinah", ayahCount: 286, startPage: 2),
        Surah(id: 3, arabic: "آل عمران", english: "Ali 'Imran", meaning: "Family of Imran", place: "madinah", ayahCount: 200, startPage: 50),
        Surah(id: 4, arabic: "النساء", english: "An-Nisa", meaning: "The Women", place: "madinah", ayahCount: 176, startPage: 77),
        Surah(id: 5, arabic: "المائدة", english: "Al-Ma'idah", meaning: "The Table Spread", place: "madinah", ayahCount: 120, startPage: 106),
        Surah(id: 6, arabic: "الأنعام", english: "Al-An'am", meaning: "The Cattle", place: "makkah", ayahCount: 165, startPage: 128),
        Surah(id: 7, arabic: "الأعراف", english: "Al-A'raf", meaning: "The Heights", place: "makkah", ayahCount: 206, startPage: 151),
        Surah(id: 8, arabic: "الأنفال", english: "Al-Anfal", meaning: "The Spoils of War", place: "madinah", ayahCount: 75, startPage: 177),
        Surah(id: 9, arabic: "التوبة", english: "At-Tawbah", meaning: "The Repentance", place: "madinah", ayahCount: 129, startPage: 187),
        Surah(id: 10, arabic: "يونس", english: "Yunus", meaning: "Jonah", place: "makkah", ayahCount: 109, startPage: 208),
        Surah(id: 11, arabic: "هود", english: "Hud", meaning: "Hud", place: "makkah", ayahCount: 123, startPage: 221),
        Surah(id: 12, arabic: "يوسف", english: "Yusuf", meaning: "Joseph", place: "makkah", ayahCount: 111, startPage: 235),
        Surah(id: 13, arabic: "الرعد", english: "Ar-Ra'd", meaning: "The Thunder", place: "madinah", ayahCount: 43, startPage: 249),
        Surah(id: 14, arabic: "ابراهيم", english: "Ibrahim", meaning: "Abraham", place: "makkah", ayahCount: 52, startPage: 255),
        Surah(id: 15, arabic: "الحجر", english: "Al-Hijr", meaning: "The Rocky Tract", place: "makkah", ayahCount: 99, startPage: 262),
        Surah(id: 16, arabic: "النحل", english: "An-Nahl", meaning: "The Bee", place: "makkah", ayahCount: 128, startPage: 267),
        Surah(id: 17, arabic: "الإسراء", english: "Al-Isra", meaning: "The Night Journey", place: "makkah", ayahCount: 111, startPage: 282),
        Surah(id: 18, arabic: "الكهف", english: "Al-Kahf", meaning: "The Cave", place: "makkah", ayahCount: 110, startPage: 293),
        Surah(id: 19, arabic: "مريم", english: "Maryam", meaning: "Mary", place: "makkah", ayahCount: 98, startPage: 305),
        Surah(id: 20, arabic: "طه", english: "Taha", meaning: "Ta-Ha", place: "makkah", ayahCount: 135, startPage: 312),
        Surah(id: 21, arabic: "الأنبياء", english: "Al-Anbya", meaning: "The Prophets", place: "makkah", ayahCount: 112, startPage: 322),
        Surah(id: 22, arabic: "الحج", english: "Al-Hajj", meaning: "The Pilgrimage", place: "madinah", ayahCount: 78, startPage: 332),
        Surah(id: 23, arabic: "المؤمنون", english: "Al-Mu'minun", meaning: "The Believers", place: "makkah", ayahCount: 118, startPage: 342),
        Surah(id: 24, arabic: "النور", english: "An-Nur", meaning: "The Light", place: "madinah", ayahCount: 64, startPage: 350),
        Surah(id: 25, arabic: "الفرقان", english: "Al-Furqan", meaning: "The Criterion", place: "makkah", ayahCount: 77, startPage: 359),
        Surah(id: 26, arabic: "الشعراء", english: "Ash-Shu'ara", meaning: "The Poets", place: "makkah", ayahCount: 227, startPage: 367),
        Surah(id: 27, arabic: "النمل", english: "An-Naml", meaning: "The Ant", place: "makkah", ayahCount: 93, startPage: 377),
        Surah(id: 28, arabic: "القصص", english: "Al-Qasas", meaning: "The Stories", place: "makkah", ayahCount: 88, startPage: 385),
        Surah(id: 29, arabic: "العنكبوت", english: "Al-'Ankabut", meaning: "The Spider", place: "makkah", ayahCount: 69, startPage: 396),
        Surah(id: 30, arabic: "الروم", english: "Ar-Rum", meaning: "The Romans", place: "makkah", ayahCount: 60, startPage: 404),
        Surah(id: 31, arabic: "لقمان", english: "Luqman", meaning: "Luqman", place: "makkah", ayahCount: 34, startPage: 411),
        Surah(id: 32, arabic: "السجدة", english: "As-Sajdah", meaning: "The Prostration", place: "makkah", ayahCount: 30, startPage: 415),
        Surah(id: 33, arabic: "الأحزاب", english: "Al-Ahzab", meaning: "The Combined Forces", place: "madinah", ayahCount: 73, startPage: 418),
        Surah(id: 34, arabic: "سبإ", english: "Saba", meaning: "Sheba", place: "makkah", ayahCount: 54, startPage: 428),
        Surah(id: 35, arabic: "فاطر", english: "Fatir", meaning: "Originator", place: "makkah", ayahCount: 45, startPage: 434),
        Surah(id: 36, arabic: "يس", english: "Ya-Sin", meaning: "Ya Sin", place: "makkah", ayahCount: 83, startPage: 440),
        Surah(id: 37, arabic: "الصافات", english: "As-Saffat", meaning: "Those who set the Ranks", place: "makkah", ayahCount: 182, startPage: 446),
        Surah(id: 38, arabic: "ص", english: "Sad", meaning: "The Letter \"Saad\"", place: "makkah", ayahCount: 88, startPage: 453),
        Surah(id: 39, arabic: "الزمر", english: "Az-Zumar", meaning: "The Troops", place: "makkah", ayahCount: 75, startPage: 458),
        Surah(id: 40, arabic: "غافر", english: "Ghafir", meaning: "The Forgiver", place: "makkah", ayahCount: 85, startPage: 467),
        Surah(id: 41, arabic: "فصلت", english: "Fussilat", meaning: "Explained in Detail", place: "makkah", ayahCount: 54, startPage: 477),
        Surah(id: 42, arabic: "الشورى", english: "Ash-Shuraa", meaning: "The Consultation", place: "makkah", ayahCount: 53, startPage: 483),
        Surah(id: 43, arabic: "الزخرف", english: "Az-Zukhruf", meaning: "The Ornaments of Gold", place: "makkah", ayahCount: 89, startPage: 489),
        Surah(id: 44, arabic: "الدخان", english: "Ad-Dukhan", meaning: "The Smoke", place: "makkah", ayahCount: 59, startPage: 496),
        Surah(id: 45, arabic: "الجاثية", english: "Al-Jathiyah", meaning: "The Crouching", place: "makkah", ayahCount: 37, startPage: 499),
        Surah(id: 46, arabic: "الأحقاف", english: "Al-Ahqaf", meaning: "The Wind-Curved Sandhills", place: "makkah", ayahCount: 35, startPage: 502),
        Surah(id: 47, arabic: "محمد", english: "Muhammad", meaning: "Muhammad", place: "madinah", ayahCount: 38, startPage: 507),
        Surah(id: 48, arabic: "الفتح", english: "Al-Fath", meaning: "The Victory", place: "madinah", ayahCount: 29, startPage: 511),
        Surah(id: 49, arabic: "الحجرات", english: "Al-Hujurat", meaning: "The Rooms", place: "madinah", ayahCount: 18, startPage: 515),
        Surah(id: 50, arabic: "ق", english: "Qaf", meaning: "The Letter \"Qaf\"", place: "makkah", ayahCount: 45, startPage: 518),
        Surah(id: 51, arabic: "الذاريات", english: "Adh-Dhariyat", meaning: "The Winnowing Winds", place: "makkah", ayahCount: 60, startPage: 520),
        Surah(id: 52, arabic: "الطور", english: "At-Tur", meaning: "The Mount", place: "makkah", ayahCount: 49, startPage: 523),
        Surah(id: 53, arabic: "النجم", english: "An-Najm", meaning: "The Star", place: "makkah", ayahCount: 62, startPage: 526),
        Surah(id: 54, arabic: "القمر", english: "Al-Qamar", meaning: "The Moon", place: "makkah", ayahCount: 55, startPage: 528),
        Surah(id: 55, arabic: "الرحمن", english: "Ar-Rahman", meaning: "The Beneficent", place: "madinah", ayahCount: 78, startPage: 531),
        Surah(id: 56, arabic: "الواقعة", english: "Al-Waqi'ah", meaning: "The Inevitable", place: "makkah", ayahCount: 96, startPage: 534),
        Surah(id: 57, arabic: "الحديد", english: "Al-Hadid", meaning: "The Iron", place: "madinah", ayahCount: 29, startPage: 537),
        Surah(id: 58, arabic: "المجادلة", english: "Al-Mujadila", meaning: "The Pleading Woman", place: "madinah", ayahCount: 22, startPage: 542),
        Surah(id: 59, arabic: "الحشر", english: "Al-Hashr", meaning: "The Exile", place: "madinah", ayahCount: 24, startPage: 545),
        Surah(id: 60, arabic: "الممتحنة", english: "Al-Mumtahanah", meaning: "She that is to be examined", place: "madinah", ayahCount: 13, startPage: 549),
        Surah(id: 61, arabic: "الصف", english: "As-Saf", meaning: "The Ranks", place: "madinah", ayahCount: 14, startPage: 551),
        Surah(id: 62, arabic: "الجمعة", english: "Al-Jumu'ah", meaning: "The Congregation, Friday", place: "madinah", ayahCount: 11, startPage: 553),
        Surah(id: 63, arabic: "المنافقون", english: "Al-Munafiqun", meaning: "The Hypocrites", place: "madinah", ayahCount: 11, startPage: 554),
        Surah(id: 64, arabic: "التغابن", english: "At-Taghabun", meaning: "The Mutual Disillusion", place: "madinah", ayahCount: 18, startPage: 556),
        Surah(id: 65, arabic: "الطلاق", english: "At-Talaq", meaning: "The Divorce", place: "madinah", ayahCount: 12, startPage: 558),
        Surah(id: 66, arabic: "التحريم", english: "At-Tahrim", meaning: "The Prohibition", place: "madinah", ayahCount: 12, startPage: 560),
        Surah(id: 67, arabic: "الملك", english: "Al-Mulk", meaning: "The Sovereignty", place: "makkah", ayahCount: 30, startPage: 562),
        Surah(id: 68, arabic: "القلم", english: "Al-Qalam", meaning: "The Pen", place: "makkah", ayahCount: 52, startPage: 564),
        Surah(id: 69, arabic: "الحاقة", english: "Al-Haqqah", meaning: "The Reality", place: "makkah", ayahCount: 52, startPage: 566),
        Surah(id: 70, arabic: "المعارج", english: "Al-Ma'arij", meaning: "The Ascending Stairways", place: "makkah", ayahCount: 44, startPage: 568),
        Surah(id: 71, arabic: "نوح", english: "Nuh", meaning: "Noah", place: "makkah", ayahCount: 28, startPage: 570),
        Surah(id: 72, arabic: "الجن", english: "Al-Jinn", meaning: "The Jinn", place: "makkah", ayahCount: 28, startPage: 572),
        Surah(id: 73, arabic: "المزمل", english: "Al-Muzzammil", meaning: "The Enshrouded One", place: "makkah", ayahCount: 20, startPage: 574),
        Surah(id: 74, arabic: "المدثر", english: "Al-Muddaththir", meaning: "The Cloaked One", place: "makkah", ayahCount: 56, startPage: 575),
        Surah(id: 75, arabic: "القيامة", english: "Al-Qiyamah", meaning: "The Resurrection", place: "makkah", ayahCount: 40, startPage: 577),
        Surah(id: 76, arabic: "الانسان", english: "Al-Insan", meaning: "The Man", place: "madinah", ayahCount: 31, startPage: 578),
        Surah(id: 77, arabic: "المرسلات", english: "Al-Mursalat", meaning: "The Emissaries", place: "makkah", ayahCount: 50, startPage: 580),
        Surah(id: 78, arabic: "النبإ", english: "An-Naba", meaning: "The Tidings", place: "makkah", ayahCount: 40, startPage: 582),
        Surah(id: 79, arabic: "النازعات", english: "An-Nazi'at", meaning: "Those who drag forth", place: "makkah", ayahCount: 46, startPage: 583),
        Surah(id: 80, arabic: "عبس", english: "'Abasa", meaning: "He Frowned", place: "makkah", ayahCount: 42, startPage: 585),
        Surah(id: 81, arabic: "التكوير", english: "At-Takwir", meaning: "The Overthrowing", place: "makkah", ayahCount: 29, startPage: 586),
        Surah(id: 82, arabic: "الإنفطار", english: "Al-Infitar", meaning: "The Cleaving", place: "makkah", ayahCount: 19, startPage: 587),
        Surah(id: 83, arabic: "المطففين", english: "Al-Mutaffifin", meaning: "The Defrauding", place: "makkah", ayahCount: 36, startPage: 587),
        Surah(id: 84, arabic: "الإنشقاق", english: "Al-Inshiqaq", meaning: "The Sundering", place: "makkah", ayahCount: 25, startPage: 589),
        Surah(id: 85, arabic: "البروج", english: "Al-Buruj", meaning: "The Mansions of the Stars", place: "makkah", ayahCount: 22, startPage: 590),
        Surah(id: 86, arabic: "الطارق", english: "At-Tariq", meaning: "The Nightcommer", place: "makkah", ayahCount: 17, startPage: 591),
        Surah(id: 87, arabic: "الأعلى", english: "Al-A'la", meaning: "The Most High", place: "makkah", ayahCount: 19, startPage: 591),
        Surah(id: 88, arabic: "الغاشية", english: "Al-Ghashiyah", meaning: "The Overwhelming", place: "makkah", ayahCount: 26, startPage: 592),
        Surah(id: 89, arabic: "الفجر", english: "Al-Fajr", meaning: "The Dawn", place: "makkah", ayahCount: 30, startPage: 593),
        Surah(id: 90, arabic: "البلد", english: "Al-Balad", meaning: "The City", place: "makkah", ayahCount: 20, startPage: 594),
        Surah(id: 91, arabic: "الشمس", english: "Ash-Shams", meaning: "The Sun", place: "makkah", ayahCount: 15, startPage: 595),
        Surah(id: 92, arabic: "الليل", english: "Al-Layl", meaning: "The Night", place: "makkah", ayahCount: 21, startPage: 595),
        Surah(id: 93, arabic: "الضحى", english: "Ad-Duhaa", meaning: "The Morning Hours", place: "makkah", ayahCount: 11, startPage: 596),
        Surah(id: 94, arabic: "الشرح", english: "Ash-Sharh", meaning: "The Relief", place: "makkah", ayahCount: 8, startPage: 596),
        Surah(id: 95, arabic: "التين", english: "At-Tin", meaning: "The Fig", place: "makkah", ayahCount: 8, startPage: 597),
        Surah(id: 96, arabic: "العلق", english: "Al-'Alaq", meaning: "The Clot", place: "makkah", ayahCount: 19, startPage: 597),
        Surah(id: 97, arabic: "القدر", english: "Al-Qadr", meaning: "The Power", place: "makkah", ayahCount: 5, startPage: 598),
        Surah(id: 98, arabic: "البينة", english: "Al-Bayyinah", meaning: "The Clear Proof", place: "madinah", ayahCount: 8, startPage: 598),
        Surah(id: 99, arabic: "الزلزلة", english: "Az-Zalzalah", meaning: "The Earthquake", place: "madinah", ayahCount: 8, startPage: 599),
        Surah(id: 100, arabic: "العاديات", english: "Al-'Adiyat", meaning: "The Courser", place: "makkah", ayahCount: 11, startPage: 599),
        Surah(id: 101, arabic: "القارعة", english: "Al-Qari'ah", meaning: "The Calamity", place: "makkah", ayahCount: 11, startPage: 600),
        Surah(id: 102, arabic: "التكاثر", english: "At-Takathur", meaning: "The Rivalry in world increase", place: "makkah", ayahCount: 8, startPage: 600),
        Surah(id: 103, arabic: "العصر", english: "Al-'Asr", meaning: "The Declining Day", place: "makkah", ayahCount: 3, startPage: 601),
        Surah(id: 104, arabic: "الهمزة", english: "Al-Humazah", meaning: "The Traducer", place: "makkah", ayahCount: 9, startPage: 601),
        Surah(id: 105, arabic: "الفيل", english: "Al-Fil", meaning: "The Elephant", place: "makkah", ayahCount: 5, startPage: 601),
        Surah(id: 106, arabic: "قريش", english: "Quraysh", meaning: "Quraysh", place: "makkah", ayahCount: 4, startPage: 602),
        Surah(id: 107, arabic: "الماعون", english: "Al-Ma'un", meaning: "The Small kindnesses", place: "makkah", ayahCount: 7, startPage: 602),
        Surah(id: 108, arabic: "الكوثر", english: "Al-Kawthar", meaning: "The Abundance", place: "makkah", ayahCount: 3, startPage: 602),
        Surah(id: 109, arabic: "الكافرون", english: "Al-Kafirun", meaning: "The Disbelievers", place: "makkah", ayahCount: 6, startPage: 603),
        Surah(id: 110, arabic: "النصر", english: "An-Nasr", meaning: "The Divine Support", place: "madinah", ayahCount: 3, startPage: 603),
        Surah(id: 111, arabic: "المسد", english: "Al-Masad", meaning: "The Palm Fiber", place: "makkah", ayahCount: 5, startPage: 603),
        Surah(id: 112, arabic: "الإخلاص", english: "Al-Ikhlas", meaning: "The Sincerity", place: "makkah", ayahCount: 4, startPage: 604),
        Surah(id: 113, arabic: "الفلق", english: "Al-Falaq", meaning: "The Daybreak", place: "makkah", ayahCount: 5, startPage: 604),
        Surah(id: 114, arabic: "الناس", english: "An-Nas", meaning: "Mankind", place: "makkah", ayahCount: 6, startPage: 604),
    ]

    static let juzStartPages: [Int] = [1, 22, 42, 62, 82, 102, 121, 142, 162, 182, 201, 222, 242, 262, 282, 302, 322, 342, 362, 382, 402, 422, 442, 462, 482, 502, 522, 542, 562, 582]
    static let hizbStartPages: [Int] = [1, 11, 22, 32, 42, 51, 62, 72, 82, 92, 102, 112, 121, 132, 142, 151, 162, 173, 182, 192, 201, 212, 222, 231, 242, 252, 262, 272, 282, 292, 302, 312, 322, 332, 342, 352, 362, 371, 382, 392, 402, 413, 422, 431, 442, 451, 462, 472, 482, 491, 502, 513, 522, 531, 542, 553, 562, 572, 582, 591]
    /// 240 rub-al-hizb (quarter) start pages; each hizb = 4 quarters.
    static let rubStartPages: [Int] = [1, 5, 7, 9, 11, 14, 17, 19, 22, 24, 27, 29, 32, 34, 37, 39, 42, 44, 46, 49, 51, 54, 56, 59, 62, 64, 67, 69, 72, 74, 77, 79, 82, 84, 87, 89, 92, 94, 97, 100, 102, 104, 106, 109, 112, 114, 117, 119, 121, 124, 126, 129, 132, 134, 137, 140, 142, 144, 146, 148, 151, 154, 156, 158, 162, 164, 167, 170, 173, 175, 177, 179, 182, 184, 187, 189, 192, 194, 196, 199, 201, 204, 206, 209, 212, 214, 217, 219, 222, 224, 226, 228, 231, 233, 236, 238, 242, 244, 247, 249, 252, 254, 256, 259, 262, 264, 267, 270, 272, 275, 277, 280, 282, 284, 287, 289, 292, 295, 297, 299, 302, 304, 306, 309, 312, 315, 317, 319, 322, 324, 326, 329, 332, 334, 336, 339, 342, 344, 347, 350, 352, 354, 356, 359, 362, 364, 367, 369, 371, 374, 377, 379, 382, 384, 386, 389, 392, 394, 396, 399, 402, 404, 407, 410, 413, 415, 418, 420, 422, 425, 426, 429, 431, 433, 436, 439, 442, 444, 446, 449, 451, 454, 456, 459, 462, 464, 467, 469, 472, 474, 477, 479, 482, 484, 486, 488, 491, 493, 496, 499, 502, 505, 507, 510, 513, 515, 517, 519, 522, 524, 526, 529, 531, 534, 536, 539, 542, 544, 547, 550, 553, 554, 558, 560, 562, 564, 566, 569, 572, 575, 577, 579, 582, 585, 587, 589, 591, 594, 596, 599]
}